In [1]:
pip install pandas pyarrow s3fs

Requirement already satisfied: pandas in /opt/conda/lib/python3.12/site-packages (2.2.3)
Requirement already satisfied: pyarrow in /opt/conda/lib/python3.12/site-packages (19.0.1)
Requirement already satisfied: s3fs in /opt/conda/lib/python3.12/site-packages (2024.10.0)
Requirement already satisfied: numpy>=1.26.0 in /opt/conda/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.12/site-packages (from pandas) (2025.1)
Requirement already satisfied: aiobotocore<3.0.0,>=2.5.4 in /opt/conda/lib/python3.12/site-packages (from s3fs) (2.21.1)
Requirement already satisfied: fsspec==2024.10.0.* in /opt/conda/lib/python3.12/site-packages (from s3fs) (2024.10.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /opt/conda/lib/python3.12/site-packages (from s3fs) (3.9.5)
Requirement already satisfied: aioitertools<1.0.0,>=0.5.1 in /opt/conda/lib/python3.12/site-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs) (0.12.0)
Requirement already satisfied: botocore<1.37.2,>=1.37.0 in /opt/conda/lib/python3.12/site-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs) (1.37.1)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/conda/lib/python3.12/site-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs) (1.0.1)
Requirement already satisfied: multidict<7.0.0,>=6.0.0 in /opt/conda/lib/python3.12/site-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs) (6.2.0)
Requirement already satisfied: wrapt<2.0.0,>=1.10.10 in /opt/conda/lib/python3.12/site-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs) (1.17.2)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (1.5.0)
Requirement already satisfied: yarl<2.0,>=1.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (1.18.3)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /opt/conda/lib/python3.12/site-packages (from botocore<1.37.2,>=1.37.0->aiobotocore<3.0.0,>=2.5.4->s3fs) (2.3.0)
Requirement already satisfied: idna>=2.0 in /opt/conda/lib/python3.12/site-packages (from yarl<2.0,>=1.0->aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (3.10)
Requirement already satisfied: propcache>=0.2.0 in /opt/conda/lib/python3.12/site-packages (from yarl<2.0,>=1.0->aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (0.2.1)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import pandas as pd
import pyarrow.parquet as pq
import s3fs

# Initialize S3 filesystem
fs = s3fs.S3FileSystem(anon=False)

# Define the base path and years/months
base_path = "path_to_glue_transformed_data"
years = ['2023', '2024']
months = [f"{i:02d}" for i in range(1, 13)]

# Gather all matching file paths
parquet_files = []
for year in years:
    for month in months:
        path = f"{base_path}/year={year}/month={month}/"
        try:
            files = fs.ls(path)
            parquet_files.extend(["s3://" + f for f in files if f.endswith(".parquet") or f.endswith(".snappy.parquet")])
        except FileNotFoundError:
            # Skip months that don't exist
            continue

# Load all Parquet files into a single DataFrame
df_list = []
for file in parquet_files:
    df = pq.ParquetDataset(file, filesystem=fs).read().to_pandas()
    df_list.append(df)

# Concatenate all dataframes
full_df = pd.concat(df_list, ignore_index=True)

# Show the resulting DataFrame
print(full_df.head())

           pickup_hour  pickup_location_id  rides  year  month
0  2023-01-01 00:00:00                   2      0  2023      1
1  2023-01-01 01:00:00                   2      0  2023      1
2  2023-01-01 02:00:00                   2      0  2023      1
3  2023-01-01 03:00:00                   2      0  2023      1
4  2023-01-01 04:00:00                   2      0  2023      1

In [5]:
full_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4394088 entries, 0 to 4394087
Data columns (total 5 columns):
 #   Column              Dtype
---  ------              -----
 0   pickup_hour         object
 1   pickup_location_id  int16
 2   rides               int16
 3   year                int32
 4   month               int32
dtypes: int16(2), int32(2), object(1)
memory usage: 83.8+ MB

In [2]:
!pip install --upgrade psycopg2-binary SQLAlchemy

Collecting psycopg2-binary
  Using cached psycopg2_binary-2.9.10-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: SQLAlchemy in /opt/conda/lib/python3.12/site-packages (2.0.39)
Collecting SQLAlchemy
  Using cached sqlalchemy-2.0.40-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.6 kB)
Requirement already satisfied: greenlet>=1 in /opt/conda/lib/python3.12/site-packages (from SQLAlchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/conda/lib/python3.12/site-packages (from SQLAlchemy) (4.12.2)
Using cached psycopg2_binary-2.9.10-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
Using cached sqlalchemy-2.0.40-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
Installing collected packages: SQLAlchemy, psycopg2-binary
  Attempting uninstall: SQLAlchemy
    Found existing installation: SQLAlchemy 2.0.39
    Uninstalling SQLAlchemy-2.0.39:
      Successfully uninstalled SQLAlchemy-2.0.39
Successfully installed SQLAlchemy-2.0.40 psycopg2-binary-2.9.10

In [ ]:
# check connection
from sqlalchemy import create_engine, text

engine = create_engine("postgresql+psycopg2://rds_user:rds_password@rds_host_name:5432/postgres")

with engine.connect() as conn:
    result = conn.execute(text("SELECT version();"))
    print(result.fetchone())

('PostgreSQL 17.2 on aarch64-unknown-linux-gnu, compiled by gcc (GCC) 12.4.0, 64-bit',)

In [ ]:
# check connection
import socket

host = "rds_host_name"
port = 5432

try:
    socket.create_connection((host, port), timeout=10)
    print("✅ Able to reach the database on port 5432")
except Exception as e:
    print(f"❌ Could not connect: {e}")

✅ Able to reach the database on port 5432

In [ ]:
import psycopg2
from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT

# Connect to default 'postgres' database to create a new one
conn = psycopg2.connect(
    dbname='postgres',
    user='rds_user',
    password='rds_password',
    host='rds_host_name',
    port=5432
)
conn.set_isolation_level(ISOLATION_LEVEL_AUTOCOMMIT)

cur = conn.cursor()
cur.execute("CREATE DATABASE taxidata_rds")
cur.close()
conn.close()

In [ ]:
from sqlalchemy import create_engine

engine = create_engine("postgresql+psycopg2://rds_user:rds_password@rds_host_name:5432/postgres")

In [9]:
full_df.to_sql('taxi_rides', con=engine, index=False, if_exists='replace', chunksize=10000)

439088

In [7]:
import pandas as pd

pd.read_sql("SELECT * from taxi_rides where pickup_location_id = '43' limit 5;", con=engine)

           pickup_hour  pickup_location_id  rides  year  month
0  2023-01-01 00:00:00                  43     87  2023      1
1  2023-01-01 01:00:00                  43     72  2023      1
2  2023-01-01 02:00:00                  43     27  2023      1
3  2023-01-01 03:00:00                  43     13  2023      1
4  2023-01-01 04:00:00                  43      3  2023      1

In [ ]:
import pandas as pd
import s3fs
import re

fs = s3fs.S3FileSystem()

bucket_base = 'mode1_predictions_bucket_base_path'
years = ['2023', '2024']

df_list = []

# List all pickup_location_id folders
location_paths = fs.ls(bucket_base)
for loc_path in location_paths:
    # Extract location ID from the folder name
    loc_match = re.search(r'pickup_location_id=(\d+)', loc_path)
    if not loc_match:
        continue
    location_id = int(loc_match.group(1))

    for year in years:
        try:
            months = fs.ls(f"{loc_path}/year={year}")
            for month_path in months:
                month_match = re.search(r'month=(\d+)', month_path)
                if not month_match:
                    continue
                month = int(month_match.group(1))
                days = fs.ls(month_path)
                for day_path in days:
                    day_match = re.search(r'day=(\d+)', day_path)
                    if not day_match:
                        continue
                    day = int(day_match.group(1))
                    hours = fs.ls(day_path)
                    for hour_path in hours:
                        hour_match = re.search(r'hour=(\d+)', hour_path)
                        if not hour_match:
                            continue
                        hour = int(hour_match.group(1))
                        file_path = f"{hour_path}/prediction.csv"
                        if fs.exists(file_path):
                            df = pd.read_csv(f"s3://{file_path}")
                            df['pickup_location_id'] = location_id
                            df['year'] = int(year)
                            df['month'] = month
                            df['day'] = day
                            df['hour'] = hour
                            df_list.append(df)
        except FileNotFoundError:
            continue

# Combine all data
predictions_df_model1 = pd.concat(df_list, ignore_index=True)

# Preview
print(predictions_df_model1.head())

   prediction_datetime  predicted_rides  pickup_location_id  year  month  day  \
0  2024-01-01 00:00:00               85                 138  2024      1    1
1  2024-01-01 01:00:00                8                 138  2024      1    1
2  2024-01-01 10:00:00              168                 138  2024      1    1
3  2024-01-01 11:00:00              147                 138  2024      1    1
4  2024-01-01 12:00:00              140                 138  2024      1    1

   hour
0     0
1     1
2    10
3    11
4    12

In [12]:
predictions_df_model1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26352 entries, 0 to 26351
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   prediction_datetime  26352 non-null  object
 1   predicted_rides      26352 non-null  int64
 2   pickup_location_id   26352 non-null  int64
 3   year                 26352 non-null  int64
 4   month                26352 non-null  int64
 5   day                  26352 non-null  int64
 6   hour                 26352 non-null  int64
dtypes: int64(6), object(1)
memory usage: 1.4+ MB

In [ ]:
from sqlalchemy import create_engine

engine = create_engine("postgresql+psycopg2://rds_user:rds_password@rds_host_name:5432/postgres")

# Load into a new table
predictions_df_model1.to_sql('predicted_rides_model1', con=engine, index=False, if_exists='replace')

352

In [8]:
pd.read_sql("SELECT DISTINCT pickup_location_id FROM predicted_rides_model1 LIMIT 5;", con=engine)

   pickup_location_id
0                 237
1                  43
2                 138

In [18]:
from sqlalchemy import text

with engine.connect() as conn:
    conn.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_taxi_rides_loc_hour
        ON taxi_rides (pickup_location_id, pickup_hour);
    """))

    conn.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_predicted_rides_loc_datetime
        ON predicted_rides_model1 (pickup_location_id, prediction_datetime);
    """))

In [19]:
from sklearn.metrics import mean_absolute_error

In [ ]:
import pandas as pd
import s3fs
import re

fs = s3fs.S3FileSystem()

bucket_base = 'model2_predictions_bucket_base_path'
years = ['2023', '2024']

df_list = []

# List all pickup_location_id folders
location_paths = fs.ls(bucket_base)
for loc_path in location_paths:
    # Extract location ID from the folder name
    loc_match = re.search(r'pickup_location_id=(\d+)', loc_path)
    if not loc_match:
        continue
    location_id = int(loc_match.group(1))

    for year in years:
        try:
            months = fs.ls(f"{loc_path}/year={year}")
            for month_path in months:
                month_match = re.search(r'month=(\d+)', month_path)
                if not month_match:
                    continue
                month = int(month_match.group(1))
                days = fs.ls(month_path)
                for day_path in days:
                    day_match = re.search(r'day=(\d+)', day_path)
                    if not day_match:
                        continue
                    day = int(day_match.group(1))
                    hours = fs.ls(day_path)
                    for hour_path in hours:
                        hour_match = re.search(r'hour=(\d+)', hour_path)
                        if not hour_match:
                            continue
                        hour = int(hour_match.group(1))
                        file_path = f"{hour_path}/prediction.csv"
                        if fs.exists(file_path):
                            df = pd.read_csv(f"s3://{file_path}")
                            df['pickup_location_id'] = location_id
                            df['year'] = int(year)
                            df['month'] = month
                            df['day'] = day
                            df['hour'] = hour
                            df_list.append(df)
        except FileNotFoundError:
            continue

# Combine all data
predictions_df_model2 = pd.concat(df_list, ignore_index=True)

# Preview
print(predictions_df_model2.head())

   prediction_datetime  predicted_rides  pickup_location_id  year  month  day  \
0  2024-01-01 00:00:00               98                 138  2024      1    1
1  2024-01-01 01:00:00               36                 138  2024      1    1
2  2024-01-01 10:00:00              135                 138  2024      1    1
3  2024-01-01 11:00:00              110                 138  2024      1    1
4  2024-01-01 12:00:00              148                 138  2024      1    1

   hour
0     0
1     1
2    10
3    11
4    12

In [2]:
predictions_df_model2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26352 entries, 0 to 26351
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   prediction_datetime  26352 non-null  object
 1   predicted_rides      26352 non-null  int64
 2   pickup_location_id   26352 non-null  int64
 3   year                 26352 non-null  int64
 4   month                26352 non-null  int64
 5   day                  26352 non-null  int64
 6   hour                 26352 non-null  int64
dtypes: int64(6), object(1)
memory usage: 1.4+ MB

In [ ]:
from sqlalchemy import create_engine

engine = create_engine("postgresql+psycopg2://rds_user:rds_password@rds_host_name:5432/postgres")

# Load into a new table
predictions_df_model2.to_sql('predicted_rides_model2', con=engine, index=False, if_exists='replace')

352

In [10]:
pd.read_sql("SELECT DISTINCT pickup_location_id FROM predicted_rides_model2 LIMIT 5;", con=engine)

   pickup_location_id
0                 237
1                  43
2                 138

In [11]:
from sqlalchemy import text

with engine.connect() as conn:
    # conn.execute(text("""
    #     CREATE INDEX IF NOT EXISTS idx_taxi_rides_loc_hour
    #     ON taxi_rides (pickup_location_id, pickup_hour);
    # """))

    conn.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_predicted_rides_loc_datetime
        ON predicted_rides_model2 (pickup_location_id, prediction_datetime);
    """))

In [12]:
import pandas as pd

pd.read_sql("SELECT * from taxi_rides where pickup_location_id = '43' limit 5;", con=engine)

           pickup_hour  pickup_location_id  rides  year  month
0  2023-01-30 08:00:00                  43     81  2023      1
1  2023-01-30 09:00:00                  43     58  2023      1
2  2023-01-30 10:00:00                  43     66  2023      1
3  2023-01-30 11:00:00                  43    100  2023      1
4  2023-01-30 12:00:00                  43     99  2023      1

In [14]:
pd.read_sql("SELECT * FROM predicted_rides_model1 LIMIT 5;", con=engine)

,prediction_datetime,predicted_rides,pickup_location_id,year,month,day,hour
0,2024-01-01 00:00:00,85,138,2024,1,1,0
1,2024-01-01 01:00:00,8,138,2024,1,1,1
2,2024-01-01 10:00:00,168,138,2024,1,1,10
3,2024-01-01 11:00:00,147,138,2024,1,1,11
4,2024-01-01 12:00:00,140,138,2024,1,1,12

In [15]:
pd.read_sql("SELECT * FROM predicted_rides_model2 LIMIT 5;", con=engine)

,prediction_datetime,predicted_rides,pickup_location_id,year,month,day,hour
0,2024-01-01 00:00:00,98,138,2024,1,1,0
1,2024-01-01 01:00:00,36,138,2024,1,1,1
2,2024-01-01 10:00:00,135,138,2024,1,1,10
3,2024-01-01 11:00:00,110,138,2024,1,1,11
4,2024-01-01 12:00:00,148,138,2024,1,1,12